-- Entfernt Tabellen aus der Datenbank
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

-- Erstellen der Tabelle fuer die Buch Genres
CREATE TABLE IF NOT EXISTS GENRES (
GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100)
);

-- Erstellen der Tabelle fuer die Buchautoren
CREATE TABLE IF NOT EXISTS AUTHORS (
AUTHOR_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
SURNAME VARCHAR(100)
);

-- Erstellen der Tabelle fuer die Buchinformationen und Verweis auf die GENRES und AUTHORS Tabelle mit Foreign Keys
-- Spalte LEND bezeichnet Buecher als Ausgeliehen (1) oder Ausleihbar (0)
CREATE TABLE IF NOT EXISTS BOOKS (
ISBN VARCHAR(13) PRIMARY KEY,
BOOK_NAME VARCHAR(255),
GENRE_ID INT,
AUTHOR_ID INT,
RELEASE_DATE DATE,
LEND INT CHECK (LEND IN(0,1)),
RETURN_DATE DATE,
FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID),
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Erstellen der Tabelle fuer die Nutzername und die Bücher, die der jeweilige Nutzer ausgeliehen hat
CREATE TABLE IF NOT EXISTS USERS (
USERNAME_ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(100),
LEND_BOOK_ISBN VARCHAR(13),
FOREIGN KEY (LEND_BOOK_ISBN) REFERENCES BOOKS(ISBN)
);

-- EINFUEGEN VON ANFANGSWERTEN IN DIE DATENBANK

INSERT INTO GENRES (NAME) VALUES ('Fantasy');
INSERT INTO AUTHORS (NAME, SURNAME) VALUES ('Tolkien', 'John');
INSERT INTO BOOKS (ISBN, BOOK_NAME, GENRE_ID, AUTHOR_ID, RELEASE_DATE, LEND)
VALUES ('0000000000000', 'The Lord Of The Rings', 1, 1, '1954-07-29', 0);

INSERT INTO GENRES (NAME) VALUES ('Thriller');
INSERT INTO AUTHORS (NAME, SURNAME) VALUES ('Tsugumi', 'Oba');
INSERT INTO BOOKS (ISBN, BOOK_NAME, GENRE_ID, AUTHOR_ID, RELEASE_DATE, LEND)
VALUES ('0000000000001', 'Death Note', 2, 2, '2003-12-01', 0);

INSERT INTO GENRES (NAME) VALUES ('Horror');
INSERT INTO AUTHORS (NAME, SURNAME) VALUES ('King', 'Stephen');
INSERT INTO BOOKS (ISBN, BOOK_NAME, GENRE_ID, AUTHOR_ID, RELEASE_DATE, LEND)
VALUES ('0000000000002', 'ES', 3, 3, '1986-09-15', 0);

INSERT INTO BOOKS (ISBN, BOOK_NAME, GENRE_ID, AUTHOR_ID, RELEASE_DATE, LEND)
VALUES ('0000000000003', 'The Dark Tower', 1, 3, '1982-06-10', 0);

-- EINFUEGEN DES ADMIN NUTZERNAMENS IN DIE DATENBANK

INSERT INTO USERS (USERNAME) VALUES ('admin');